version: '3.9'

services:
  postgres:
    image: postgres:17.4
    container_name: loop-room-pg
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5430:5432'
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/postgresql
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d main']
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

  valkey:
    image: valkey/valkey:8.1
    container_name: loop-room-kv
    ports:
      - '127.0.0.1:6379:6379'
    command: valkey-server --port 6379
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    security_opt:
      - no-new-privileges:true
    read_only: true

volumes:
  pgdata:
    driver: local
